export enum DroneModel {
  PHANTOM_4 = 'PHANTOM_4',
  MATRICE_300 = 'MATRICE_300',
  MAVIC_3_ENTERPRISE = 'MAVIC_3_ENTERPRISE',
}

export enum DroneStatus {
  AVAILABLE = 'AVAILABLE',
  IN_MISSION = 'IN_MISSION',
  MAINTENANCE = 'MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum MissionType {
  WIND_TURBINE_INSPECTION = 'WIND_TURBINE_INSPECTION',
  SOLAR_PANEL_SURVEY = 'SOLAR_PANEL_SURVEY',
  POWER_LINE_PATROL = 'POWER_LINE_PATROL',
}

export enum MissionStatus {
  PLANNED = 'PLANNED',
  PRE_FLIGHT_CHECK = 'PRE_FLIGHT_CHECK',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ABORTED = 'ABORTED',
}

export enum MaintenanceType {
  ROUTINE_CHECK = 'ROUTINE_CHECK',
  BATTERY_REPLACEMENT = 'BATTERY_REPLACEMENT',
  MOTOR_REPAIR = 'MOTOR_REPAIR',
  FIRMWARE_UPDATE = 'FIRMWARE_UPDATE',
  FULL_OVERHAUL = 'FULL_OVERHAUL',
}
